####################
### local routes ###
####################


### Get all customers
GET http://localhost:8080/customers/
Authorization: Bearer {{authToken}}

### post new customer
POST http://localhost:8080/customers/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{   
    "firstName": "Tom",
    "lastName": "Kesterson",
    "email": "TomKester@notreal.email"

}

### update customer by id
PUT http://localhost:8080/customers/68fbb22168b908668012bda0
Content-Type: application/json
Authorization: Bearer {{authToken}}

{   
    "firstName": "Beth",
    "lastName": "Kester",
    "email": "BethKester@notreal.email"

}

### delete customer
DELETE http://localhost:8080/customers/68fa7b718c343811715c781c
Authorization: Bearer {{authToken}}


####################
### public routes ###
####################


### Get all customers
GET https://ticketer-71yh.onrender.com/customers/
Authorization: Bearer {{authToken}}

### post new customer
POST https://ticketer-71yh.onrender.com/customers/
Content-Type: application/json
Authorization: Bearer {{authToken}}

{   
    "firstName": "Willy",
    "lastName": "Wonka",
    "email": "unrealemaiL@tom.email"

}


### update customer by id
PUT https://ticketer-71yh.onrender.com/customers/68fcffd62bac584742d8d865
Content-Type: application/json
Authorization: Bearer {{authToken}}

{   
    "firstName": "Beth",
    "lastName": "Kester",
    "email": "BethKester55@notreal.com"

}

### delete customer
DELETE https://ticketer-71yh.onrender.com/customers/68fcfe522bac584742d8d864
Authorization: Bearer {{authToken}}


