####################
### local routes ###
####################

### Get all customers
GET http://localhost:8080/customers/

### post new customer
POST http://localhost:8080/customers/
Content-Type: application/json

{   
    "firstName": "Tom",
    "lastName": "Kester",
    "email": "TomKester@notreal.email"

}

### update customer by id
PUT http://localhost:8080/customers/68fa7a81548cb7d417ae9eb6
Content-Type: application/json

{   
    "firstName": "Beth",
    "lastName": "Kester",
    "email": "BethKester@notreal.email"

}

### delete customer
DELETE http://localhost:8080/customers/68fa7a81548cb7d417ae9eb6


####################
### public routes ###
####################


### Get all customers
GET https://ticketer-71yh.onrender.com/customers/

### post new customer
POST https://ticketer-71yh.onrender.com/customers/
Content-Type: application/json

{   
    "firstName": "Willy",
    "lastName": "Wonka",
    "email": "unrealemaiL@tom.email"

}


### update customer by id
PUT http://localhost:8080/customers/68fa7a81548cb7d417ae9eb6
Content-Type: application/json

{   
    "firstName": "Beth",
    "lastName": "Kester",
    "email": "BethKester@notreal.email"

}

### delete customer
DELETE http://localhost:8080/customers/68fa7a81548cb7d417ae9eb6



